/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoviePopularRouteImport } from './routes/movie/popular'
import { Route as MovieFavoriteRouteImport } from './routes/movie/favorite'
import { Route as MovieAiringNowRouteImport } from './routes/movie/airing-now'
import { Route as MovieMovieIdRouteImport } from './routes/movie/$movieId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviePopularRoute = MoviePopularRouteImport.update({
  id: '/movie/popular',
  path: '/movie/popular',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieFavoriteRoute = MovieFavoriteRouteImport.update({
  id: '/movie/favorite',
  path: '/movie/favorite',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieAiringNowRoute = MovieAiringNowRouteImport.update({
  id: '/movie/airing-now',
  path: '/movie/airing-now',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieMovieIdRoute = MovieMovieIdRouteImport.update({
  id: '/movie/$movieId',
  path: '/movie/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
  '/movie/airing-now': typeof MovieAiringNowRoute
  '/movie/favorite': typeof MovieFavoriteRoute
  '/movie/popular': typeof MoviePopularRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
  '/movie/airing-now': typeof MovieAiringNowRoute
  '/movie/favorite': typeof MovieFavoriteRoute
  '/movie/popular': typeof MoviePopularRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
  '/movie/airing-now': typeof MovieAiringNowRoute
  '/movie/favorite': typeof MovieFavoriteRoute
  '/movie/popular': typeof MoviePopularRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/movie/$movieId'
    | '/movie/airing-now'
    | '/movie/favorite'
    | '/movie/popular'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/movie/$movieId'
    | '/movie/airing-now'
    | '/movie/favorite'
    | '/movie/popular'
  id:
    | '__root__'
    | '/'
    | '/movie/$movieId'
    | '/movie/airing-now'
    | '/movie/favorite'
    | '/movie/popular'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MovieMovieIdRoute: typeof MovieMovieIdRoute
  MovieAiringNowRoute: typeof MovieAiringNowRoute
  MovieFavoriteRoute: typeof MovieFavoriteRoute
  MoviePopularRoute: typeof MoviePopularRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/popular': {
      id: '/movie/popular'
      path: '/movie/popular'
      fullPath: '/movie/popular'
      preLoaderRoute: typeof MoviePopularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/favorite': {
      id: '/movie/favorite'
      path: '/movie/favorite'
      fullPath: '/movie/favorite'
      preLoaderRoute: typeof MovieFavoriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/airing-now': {
      id: '/movie/airing-now'
      path: '/movie/airing-now'
      fullPath: '/movie/airing-now'
      preLoaderRoute: typeof MovieAiringNowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$movieId': {
      id: '/movie/$movieId'
      path: '/movie/$movieId'
      fullPath: '/movie/$movieId'
      preLoaderRoute: typeof MovieMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MovieMovieIdRoute: MovieMovieIdRoute,
  MovieAiringNowRoute: MovieAiringNowRoute,
  MovieFavoriteRoute: MovieFavoriteRoute,
  MoviePopularRoute: MoviePopularRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
