/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoviePopularRouteImport } from './routes/movie/popular'
import { Route as MovieFavoriteRouteImport } from './routes/movie/favorite'
import { Route as MovieAiringNowRouteImport } from './routes/movie/airing-now'
import { Route as MovieMovieIdRouteImport } from './routes/movie/$movieId'
import { Route as MovieMovieIdTrailerRouteImport } from './routes/movie/$movieId.trailer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviePopularRoute = MoviePopularRouteImport.update({
  id: '/movie/popular',
  path: '/movie/popular',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieFavoriteRoute = MovieFavoriteRouteImport.update({
  id: '/movie/favorite',
  path: '/movie/favorite',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieAiringNowRoute = MovieAiringNowRouteImport.update({
  id: '/movie/airing-now',
  path: '/movie/airing-now',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieMovieIdRoute = MovieMovieIdRouteImport.update({
  id: '/movie/$movieId',
  path: '/movie/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieMovieIdTrailerRoute = MovieMovieIdTrailerRouteImport.update({
  id: '/trailer',
  path: '/trailer',
  getParentRoute: () => MovieMovieIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/movie/$movieId': typeof MovieMovieIdRouteWithChildren
  '/movie/airing-now': typeof MovieAiringNowRoute
  '/movie/favorite': typeof MovieFavoriteRoute
  '/movie/popular': typeof MoviePopularRoute
  '/movie/$movieId/trailer': typeof MovieMovieIdTrailerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/movie/$movieId': typeof MovieMovieIdRouteWithChildren
  '/movie/airing-now': typeof MovieAiringNowRoute
  '/movie/favorite': typeof MovieFavoriteRoute
  '/movie/popular': typeof MoviePopularRoute
  '/movie/$movieId/trailer': typeof MovieMovieIdTrailerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/movie/$movieId': typeof MovieMovieIdRouteWithChildren
  '/movie/airing-now': typeof MovieAiringNowRoute
  '/movie/favorite': typeof MovieFavoriteRoute
  '/movie/popular': typeof MoviePopularRoute
  '/movie/$movieId/trailer': typeof MovieMovieIdTrailerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/movie/$movieId'
    | '/movie/airing-now'
    | '/movie/favorite'
    | '/movie/popular'
    | '/movie/$movieId/trailer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/movie/$movieId'
    | '/movie/airing-now'
    | '/movie/favorite'
    | '/movie/popular'
    | '/movie/$movieId/trailer'
  id:
    | '__root__'
    | '/'
    | '/movie/$movieId'
    | '/movie/airing-now'
    | '/movie/favorite'
    | '/movie/popular'
    | '/movie/$movieId/trailer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MovieMovieIdRoute: typeof MovieMovieIdRouteWithChildren
  MovieAiringNowRoute: typeof MovieAiringNowRoute
  MovieFavoriteRoute: typeof MovieFavoriteRoute
  MoviePopularRoute: typeof MoviePopularRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/popular': {
      id: '/movie/popular'
      path: '/movie/popular'
      fullPath: '/movie/popular'
      preLoaderRoute: typeof MoviePopularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/favorite': {
      id: '/movie/favorite'
      path: '/movie/favorite'
      fullPath: '/movie/favorite'
      preLoaderRoute: typeof MovieFavoriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/airing-now': {
      id: '/movie/airing-now'
      path: '/movie/airing-now'
      fullPath: '/movie/airing-now'
      preLoaderRoute: typeof MovieAiringNowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$movieId': {
      id: '/movie/$movieId'
      path: '/movie/$movieId'
      fullPath: '/movie/$movieId'
      preLoaderRoute: typeof MovieMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$movieId/trailer': {
      id: '/movie/$movieId/trailer'
      path: '/trailer'
      fullPath: '/movie/$movieId/trailer'
      preLoaderRoute: typeof MovieMovieIdTrailerRouteImport
      parentRoute: typeof MovieMovieIdRoute
    }
  }
}

interface MovieMovieIdRouteChildren {
  MovieMovieIdTrailerRoute: typeof MovieMovieIdTrailerRoute
}

const MovieMovieIdRouteChildren: MovieMovieIdRouteChildren = {
  MovieMovieIdTrailerRoute: MovieMovieIdTrailerRoute,
}

const MovieMovieIdRouteWithChildren = MovieMovieIdRoute._addFileChildren(
  MovieMovieIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MovieMovieIdRoute: MovieMovieIdRouteWithChildren,
  MovieAiringNowRoute: MovieAiringNowRoute,
  MovieFavoriteRoute: MovieFavoriteRoute,
  MoviePopularRoute: MoviePopularRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
